INSERT INTO USERS(USERNAME,PASSWORD) VALUES ('Binod@gmail.com', '$2a$12$FevV6PACKqVj64lhklkjU.A6GWPdAyhwy4.svc6lBB9JZfFTse0a2');
INSERT INTO PRIVILEGE(NAME) VALUES('READ');
INSERT INTO PRIVILEGE(NAME) VALUES('WRITE');
INSERT INTO USER_PRIVELEGES(USER_ID,PRIVILEGE_ID) VALUES ('1','1');
INSERT INTO USER_PRIVELEGES(USER_ID,PRIVILEGE_ID) VALUES ('1','2');